teams:
- name: test
  maintainers:
  - zhzhuang-zju
  members:
  - JesseStutler
- name: sig-dashboard
  maintainers:
  - JesseStutler
repositories:
- name: team-test
  teams:
    test: read
  visibility: public
- name: dashboard
  teams:
    sig-dashboard: maintain
  visibility: public 
