apiVersion: v1
kind: Secret
metadata:
  name: ${component}-config
  namespace: karmada-system
stringData:
  karmada.config: |-
    apiVersion: v1
    kind: Config
    preferences: {}
    clusters:
    - name: karmada-apiserver
      cluster:
        certificate-authority-data: ${ca_crt}
        server: https://karmada-apiserver.karmada-system.svc.cluster.local:5443
    users:
    - name: karmada-apiserver
      user:
        client-certificate-data: ${client_crt}
        client-key-data: ${client_key}
    contexts:
    - name: karmada-apiserver
      context:
        cluster: karmada-apiserver
        user: karmada-apiserver
    current-context: karmada-apiserver
